# Generated by Django 5.0.4 on 2024-04-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("book_image", models.ImageField(blank=True, upload_to="")),
                ("book_genre", models.CharField(max_length=100)),
                ("book_author", models.CharField(max_length=100)),
            ],
        ),
    ]
