# Generated by Django 5.0 on 2024-04-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors_Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="books",
            name="book_author",
        ),
        migrations.AddField(
            model_name="books",
            name="book_author",
            field=models.ManyToManyField(default="authors", to="my_app.authors_name"),
        ),
    ]
