# Generated by Django 5.0 on 2024-04-17 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_books_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
