# Generated by Django 5.0 on 2024-04-18 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_books_favourites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="favourites",
            field=models.ManyToManyField(
                blank=True, default=False, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
